// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import ScrollTo from 'stimulus-scroll-to'
application.register('scroll-to', ScrollTo)

import HomeController from "./home_controller"
application.register("home", HomeController)